SELECT * from POST_PROPERTY;


INSERT INTO POST_PROPERTY(PROPERTY_TYPE_ID,PROPERTY_TYPE_GROUP_ID, BUILDING_NAME, TRANSACTION_TYPE_ID, CONFIGURATION_ID, AVAILABILITY_ID, CREATED_BY, UPDATED_BY
)
VALUES(1,1, 'New Building', 1, 1, 3,'System-User','System-User');
