SELECT * from post_property pp ;

desc post_property ;

select PROPERTY_TYPE_TITLE, BUILDING_NAME, BUILDER_NAME,  ADDRESS_LINE_1, CITY_NAME, AVAILABILITY_TITLE, UPDATED_TS from POST_PROPERTY;

SELECT * from post_property pp  where BUILDER_NAME  = 'Kanika';

SELECT PROPERTY_ID, TEMPLATE_ID, PROJECT_NAME, PROPERTY_TYPE_ID, PROPERTY_TYPE_TITLE, PROPERTY_TYPE_GROUP_ID, PROPERTY_TYPE_GROUP_TITLE, BUILDING_NAME, BUILDER_NAME, BUILDER_WEB_URL, TRANSACTION_TYPE_ID, TRANSACTION_TYPE_TITLE, CONFIGURATION_ID, CONFIGURATION_TITLE, ADDRESS_LINE_1, ADDRESS_LINE_2, LOCALITY_IDS, LOCALITY_TITLES, CITY_NAME, AREA_NAME, STATE_NAME, LANDMARK_NAME, PIN_CODE, COUNTRY_NAME, AVAILABILITY_ID, AVAILABILITY_TITLE, AVAILABILITY_TS, PROPERTY_AGE_ID, PROPERTY_AGE_TITLE, PROPERTY_DESCRIPTION, TOTAL_BEDROOMS, TOTAL_MASTER_BEDROOMS, TOTAL_BATHROOMS, TOTAL_BALCONIES, SUPER_BUILT_UP_AREA, SUPER_BUILT_UP_AREA_UNIT_ID, SUPER_BUILT_UP_AREA_UNIT_TITLE, BUILT_UP_AREA, BUILT_UP_AREA_UNIT_ID, BUILT_UP_AREA_UNIT_TITLE, CARPET_AREA, CARPET_AREA_UNIT_ID, CARPET_AREA_UNIT_TITLE, FURNISH_TYPE_ID, FURNISH_TYPE_TITLE, FLOOR_ID, FLOOR_NO, TOTAL_FLOORS, TOTAL_FLATS_FLOOR, TOTAL_COVERED_PARKING, TOTAL_OPEN_PARKING, TOTAL_BUILDING_COVERED_PARKING, TOTAL_BUILDING_OPEN_PARKING, TOTAL_BUILDING_VISITOR_PARKING, FACE_ID, FACE_TITLE, OVERLOOK_IDS, OVERLOOK_TITLES, FLOOR_TYPE_IDS, FLOOR_TYPE_TITLES, MODULAR_KITCHEN, POOJA_ROOM, STUDY_ROOM, SERVANT_ROOM, OTHERS_ROOM, AMOUNT_NEGOTIABLE, MAINTENANCE_AMOUNT, MAINTENANCE_PERIOD_ID, MAINTENANCE_PERIOD_TITLE, HEAVY_DEPOSIT, EXPECTED_DEPOSIT_AMOUNT, EXPECTED_RENTAL_AMOUNT, EXPECTED_AMOUNT, ALL_INCLUSIVE_PRICE, TAX_AND_GOV_CHARGE_INCLUDED, NOTES, TOTAL_BROKER, WEEKDAYS_VISIT_TIME_IDS, WEEKDAYS_VISIT_TIME_TITLES, WEEKEND_VISIT_TIME_IDS, WEEKEND_VISIT_TIME_TITLES, EARTHQUAKE_RESISTANT, GAS_PIPELINE, CLUB_HOUSE, GYM, KIDS_PLAY_AREA, WATER_HARVESTING, SWIMMING_POOL, COMMON_AREA_POWER_BACKUP, FLAT_POWER_BACKUP, SENIOR_CITIZEN_AREA, GATED_SOCIETY, WATER_SUPPLY, LANDSCAPE_LAWN, BANQUET_HALL, JOGGERS_TRACK, CCTV, FIRE_ALARM, PET_FRIENDLY, TOTAL_SERVICE_LIFT, TOTAL_LIFT, OC_TS, RERA_ID, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, POSTED_BY, POSTED_TS, POSTED_USER_TYPE_ID, POSTED_USER_TYPE_TITLE, UPDATED_TS, DEAL_TS
FROM POST_PROPERTY ;

SELECT * from APP_REF_DATA ard where DATA_TYPE  like '%TR%';


String DB_REALTY_PROPERTY_COLUMN_POSTED_BY = "POSTED_BY";
    String DB_REALTY_PROPERTY_COLUMN_POSTED_TS = "POSTED_TS";
    String DB_REALTY_PROPERTY_COLUMN_POSTED_USER_TYPE_ID = "POSTED_USER_TYPE_ID";
    String DB_REALTY_PROPERTY_COLUMN_POSTED_USER_TYPE_TITLE = "POSTED_USER_TYPE_TITLE";
    String DB_REALTY_PROPERTY_COLUMN_DEAL_TS = "DEAL_TS";
   
;

PROJECT_NAME,
PROPERTY_TYPE_TITLE,
PROPERTY_TYPE_GROUP_TITLE
BUILDING_NAME
BUILDER_NAME
TRANSACTION_TYPE_TITLE
CONFIGURATION_TITLE
ADDRESS_LINE_1
ADDRESS_LINE_2
LOCALITY_TITLES
CITY_NAME
AREA_NAME
STATE_NAME
LANDMARK_NAME
PIN_CODE
AVAILABILITY_TITLE
PROPERTY_AGE_TITLE
FURNISH_TYPE_TITLE
RERA_ID
POSTED_BY_NAME
POSTED_USER_TYPE_TITLE
SALE_TYPE_TITLE
TENANT_TYPE_TITLE


EXPECTED_AMOUNT
EXPECTED_RENTAL_AMOUNT
;
DESC post_property ;






select * From POST_PROPERTY pp ;

select * From POST_PROPERTY pp where GYM  = 1;

