

-- ============================   APP_REF_DATA ===========================
CREATE TABLE APP_REF_DATA(
	DATA_ID	BIGINT NOT NULL AUTO_INCREMENT,
	DATA_TYPE	VARCHAR (255) NOT NULL,
	DATA_KEY	VARCHAR (255) NOT NULL,
	DATA_VALUE	VARCHAR (255),
	GROUP_NAME	VARCHAR (255) NOT NULL DEFAULT 'DEFAULT',
	SUB_GROUP_NAME	VARCHAR (255),
	APP_NAME	VARCHAR (255) NOT NULL,
	MODULE_NAME	VARCHAR (255) NOT NULL,
	STATUS_ID	INT NOT NULL DEFAULT 1,
	STATUS_TITLE	VARCHAR (255),
	CREATED_BY	VARCHAR (255) NOT NULL, 
	CREATED_TS	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY	VARCHAR (255) NOT NULL,
	UPDATED_TS	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT APP_REF_DATA_PK_DATA_ID PRIMARY KEY(DATA_ID),
	CONSTRAINT APP_REF_DATA_UK_DATA_TYPE_KEY UNIQUE (DATA_TYPE,DATA_KEY)
	);
