package com.paroont.core.db.constant.common;


public interface CoreDbCommonColumnConst {
    // Add Only Common DB Column Const, Pattern: DB_COMMON_COLUMN_[COLUMN_NAME].

    String DB_COMMON_COLUMN_USER_ID = "USER_ID";
    String DB_COMMON_COLUMN_LOGIN_ID = "LOGIN_ID";
    String DB_COMMON_COLUMN_USER_NAME = "USER_NAME";

    String DB_COMMON_COLUMN_FIRST_NAME = "FIRST_NAME";
    String DB_COMMON_COLUMN_LAST_NAME = "LAST_NAME";

    String DB_COMMON_COLUMN_STATUS_ID = "STATUS_ID";
    String DB_COMMON_COLUMN_STATUS_TITLE = "STATUS_TITLE";

    String DB_COMMON_COLUMN_CREATED_BY = "CREATED_BY";
    String DB_COMMON_COLUMN_CREATED_TS = "CREATED_TS";

    String DB_COMMON_COLUMN_UPDATED_BY = "UPDATED_BY";
    String DB_COMMON_COLUMN_UPDATED_TS = "UPDATED_TS";

    String DB_COMMON_COLUMN_GROUP_NAME = "GROUP_NAME";
    String DB_COMMON_COLUMN_SUB_GROUP_NAME = "SUB_GROUP_NAME";

    String DB_COMMON_COLUMN_APP_NAME = "APP_NAME";
    String DB_COMMON_COLUMN_MODULE_NAME = "MODULE_NAME";


    String DB_COMMON_COLUMN_EMAIL_ID = "EMAIL_ID";
    String DB_COMMON_COLUMN_EMAIL_ID_2 = "EMAIL_ID_2";
    String DB_COMMON_COLUMN_EMAIL_ID_3 = "EMAIL_ID_3";

    String DB_COMMON_COLUMN_COMPANY_NAME = "COMPANY_NAME";
    String DB_COMMON_COLUMN_COMPANY_WEB_URL = "COMPANY_WEB_URL";
    String DB_COMMON_COLUMN_COMPANY_OVERVIEW = "COMPANY_OVERVIEW";

    String DB_COMMON_COLUMN_FACEBOOK_ID = "FACEBOOK_ID";
    String DB_COMMON_COLUMN_TWITTER_ID = "TWITTER_ID";
    String DB_COMMON_COLUMN_INSTAGRAM_ID = "INSTAGRAM_ID";
    String DB_COMMON_COLUMN_WHATSAPP_NO = "WHATSAPP_NO";
    String DB_COMMON_COLUMN_WHATSAPP_COUNTRY_CODE = "WHATSAPP_COUNTRY_CODE";

    String DB_COMMON_COLUMN_MOBILE_NO = "MOBILE_NO";
    String DB_COMMON_COLUMN_MOBILE_COUNTRY_CODE = "MOBILE_COUNTRY_CODE";

    String DB_COMMON_COLUMN_CONTACT_NO_2 = "CONTACT_NO_2";
    String DB_COMMON_COLUMN_CONTACT_NO_2_COUNTRY_CODE = "CONTACT_NO_2_COUNTRY_CODE";
    String DB_COMMON_COLUMN_CONTACT_NO_2_TITLE = "CONTACT_NO_2_TITLE";

    String DB_COMMON_COLUMN_CONTACT_NO_3 = "CONTACT_NO_3";
    String DB_COMMON_COLUMN_CONTACT_NO_3_COUNTRY_CODE = "CONTACT_NO_3_COUNTRY_CODE";
    String DB_COMMON_COLUMN_CONTACT_NO_3_TITLE = "CONTACT_NO_3_TITLE";

    String DB_COMMON_COLUMN_ADDRESS_LINE_1 = "ADDRESS_LINE_1";
    String DB_COMMON_COLUMN_ADDRESS_LINE_2 = "ADDRESS_LINE_2";

    String DB_COMMON_COLUMN_LOCALITY_NAME = "LOCALITY_NAME";
    String DB_COMMON_COLUMN_CITY_NAME = "CITY_NAME";
    String DB_COMMON_COLUMN_AREA_NAME = "AREA_NAME";
    String DB_COMMON_COLUMN_STATE_NAME = "STATE_NAME";
    String DB_COMMON_COLUMN_LANDMARK_NAME = "LANDMARK_NAME";
    String DB_COMMON_COLUMN_PIN_CODE = "PIN_CODE";
    String DB_COMMON_COLUMN_COUNTRY_NAME = "COUNTRY_NAME";

    String DB_COMMON_COLUMN_GENDER_TITLE = "GENDER_TITLE";
    String DB_COMMON_COLUMN_DOB = "DOB";

    String DB_COMMON_COLUMN_TEMPLATE_ID = "TEMPLATE_ID";

    String DB_COMMON_COLUMN_PROJECT_ID = "PROJECT_ID";
    String DB_COMMON_COLUMN_PROJECT_NAME = "PROJECT_NAME";

    String DB_COMMON_COLUMN_NOTES = "NOTES";
    String DB_COMMON_COLUMN_USER_COMMENTS = "USER_COMMENTS";
    String DB_COMMON_COLUMN_SYSTEM_COMMENTS = "SYSTEM_COMMENTS";

    // AUDIT
    String DB_COMMON_COLUMN_AUDIT_ID = "AUDIT_ID";
    String DB_COMMON_COLUMN_AUDIT_ACTION_ID = "AUDIT_ACTION_ID";
    String DB_COMMON_COLUMN_AUDIT_ACTION_TITLE = "AUDIT_ACTION_TITLE";
    String DB_COMMON_COLUMN_AUDIT_ACTION_TS = "AUDIT_ACTION_TS";
    String DB_COMMON_COLUMN_AUDIT_USER_ID = "AUDIT_USER_ID";
    String DB_COMMON_COLUMN_AUDIT_LOGIN_ID = "AUDIT_LOGIN_ID";
    String DB_COMMON_COLUMN_AUDIT_DB_USER_ID = "AUDIT_DB_USER_ID";

}
