package com.rsatech.realty.core.db.constant.property;

import static com.rsatech.core.db.constant.profile.CoreProfileDbConst.DB_COMMON_COMPANY_PROFILE_COLUMNS;
import static com.rsatech.core.db.constant.profile.CoreProfileDbConst.DB_COMMON_COMPANY_PROFILE_COLUMNS_PARAMS;
// Add Only DB SQL Const for Property
public interface PropertyDbConstant {

    // ====================   Column Constant   =======================
    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_ID = "PROPERTY_ID";
    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_TYPE_ID = "PROPERTY_TYPE_ID";
    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_TYPE_TITLE = "PROPERTY_TYPE_TITLE";
    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_TYPE_GROUP_ID = "PROPERTY_TYPE_GROUP_ID";
    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_TYPE_GROUP_TITLE = "PROPERTY_TYPE_GROUP_TITLE";

    String DB_REALTY_PROPERTY_COLUMN_BUILDING_NAME = "BUILDING_NAME";
    String DB_REALTY_PROPERTY_COLUMN_BUILDER_NAME = "BUILDER_NAME";
    String DB_REALTY_PROPERTY_COLUMN_BUILDER_WEB_URL = "BUILDER_WEB_URL";

    String DB_REALTY_PROPERTY_COLUMN_TRANSACTION_TYPE_ID = "TRANSACTION_TYPE_ID";
    String DB_REALTY_PROPERTY_COLUMN_TRANSACTION_TYPE_TITLE = "TRANSACTION_TYPE_TITLE";
    String DB_REALTY_PROPERTY_COLUMN_CONFIGURATION_ID = "CONFIGURATION_ID";
    String DB_REALTY_PROPERTY_COLUMN_CONFIGURATION_TITLE = "CONFIGURATION_TITLE";

    String DB_REALTY_PROPERTY_COLUMN_LOCALITY_IDS = "LOCALITY_IDS";
    String DB_REALTY_PROPERTY_COLUMN_LOCALITY_TITLES = "LOCALITY_TITLES";

    String DB_REALTY_PROPERTY_COLUMN_AVAILABILITY_ID = "AVAILABILITY_ID";
    String DB_REALTY_PROPERTY_COLUMN_AVAILABILITY_TITLE = "AVAILABILITY_TITLE";
    String DB_REALTY_PROPERTY_COLUMN_AVAILABILITY_TS = "AVAILABILITY_TS";

    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_AGE_ID = "PROPERTY_AGE_ID";
    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_AGE_TITLE = "PROPERTY_AGE_TITLE";
    String DB_REALTY_PROPERTY_COLUMN_PROPERTY_DESCRIPTION = "PROPERTY_DESCRIPTION";

    String DB_REALTY_PROPERTY_COLUMN_TOTAL_BEDROOMS = "TOTAL_BEDROOMS";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_MASTER_BEDROOMS = "TOTAL_MASTER_BEDROOMS";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_BATHROOMS = "TOTAL_BATHROOMS";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_BALCONIES = "TOTAL_BALCONIES";

    String DB_REALTY_PROPERTY_COLUMN_SUPER_BUILT_UP_AREA = "SUPER_BUILT_UP_AREA";
    String DB_REALTY_PROPERTY_COLUMN_SUPER_BUILT_UP_AREA_UNIT_ID = "SUPER_BUILT_UP_AREA_UNIT_ID";
    String DB_REALTY_PROPERTY_COLUMN_SUPER_BUILT_UP_AREA_UNIT_TITLE = "SUPER_BUILT_UP_AREA_UNIT_TITLE";

    String DB_REALTY_PROPERTY_COLUMN_BUILT_UP_AREA = "BUILT_UP_AREA";
    String DB_REALTY_PROPERTY_COLUMN_BUILT_UP_AREA_UNIT_ID = "BUILT_UP_AREA_UNIT_ID";
    String DB_REALTY_PROPERTY_COLUMN_BUILT_UP_AREA_UNIT_TITLE = "BUILT_UP_AREA_UNIT_TITLE";

    String DB_REALTY_PROPERTY_COLUMN_CARPET_AREA = "CARPET_AREA";
    String DB_REALTY_PROPERTY_COLUMN_CARPET_AREA_UNIT_ID = "CARPET_AREA_UNIT_ID";
    String DB_REALTY_PROPERTY_COLUMN_CARPET_AREA_UNIT_TITLE = "CARPET_AREA_UNIT_TITLE";

    String DB_REALTY_PROPERTY_COLUMN_FLOOR_ID = "FLOOR_ID";
    String DB_REALTY_PROPERTY_COLUMN_FLOOR_NO = "FLOOR_NO";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_FLOORS = "TOTAL_FLOORS";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_FLATS_FLOOR = "TOTAL_FLATS_FLOOR";

    String DB_REALTY_PROPERTY_COLUMN_TOTAL_COVERED_PARKING = "TOTAL_COVERED_PARKING";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_OPEN_PARKING = "TOTAL_OPEN_PARKING";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_BUILDING_COVERED_PARKING = "TOTAL_BUILDING_COVERED_PARKING";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_BUILDING_OPEN_PARKING = "TOTAL_BUILDING_OPEN_PARKING";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_BUILDING_VISITOR_PARKING = "TOTAL_BUILDING_VISITOR_PARKING";

    String DB_REALTY_PROPERTY_COLUMN_FURNISH_TYPE_ID = "FURNISH_TYPE_ID";
    String DB_REALTY_PROPERTY_COLUMN_FURNISH_TYPE_TITLE = "FURNISH_TYPE_TITLE";

    String DB_REALTY_PROPERTY_COLUMN_FACE_ID = "FACE_ID";
    String DB_REALTY_PROPERTY_COLUMN_FACE_TITLE = "FACE_TITLE";

    String DB_REALTY_PROPERTY_COLUMN_OVERLOOK_IDS = "OVERLOOK_IDS";
    String DB_REALTY_PROPERTY_COLUMN_OVERLOOK_TITLES = "OVERLOOK_TITLES";

    String DB_REALTY_PROPERTY_COLUMN_FLOOR_TYPE_IDS = "FLOOR_TYPE_IDS";
    String DB_REALTY_PROPERTY_COLUMN_FLOOR_TYPE_TITLES = "FLOOR_TYPE_TITLES";

    String DB_REALTY_PROPERTY_COLUMN_MODULAR_KITCHEN = "MODULAR_KITCHEN";
    String DB_REALTY_PROPERTY_COLUMN_POOJA_ROOM = "POOJA_ROOM";
    String DB_REALTY_PROPERTY_COLUMN_STUDY_ROOM = "STUDY_ROOM";
    String DB_REALTY_PROPERTY_COLUMN_SERVANT_ROOM = "SERVANT_ROOM";
    String DB_REALTY_PROPERTY_COLUMN_OTHERS_ROOM = "OTHERS_ROOM";

    String DB_REALTY_PROPERTY_COLUMN_AMOUNT_NEGOTIABLE = "AMOUNT_NEGOTIABLE";
    String DB_REALTY_PROPERTY_COLUMN_MAINTENANCE_AMOUNT = "MAINTENANCE_AMOUNT";
    String DB_REALTY_PROPERTY_COLUMN_MAINTENANCE_PERIOD_ID = "MAINTENANCE_PERIOD_ID";

    String DB_REALTY_PROPERTY_COLUMN_MAINTENANCE_PERIOD_TITLE = "MAINTENANCE_PERIOD_TITLE";
    String DB_REALTY_PROPERTY_COLUMN_HEAVY_DEPOSIT = "HEAVY_DEPOSIT";
    String DB_REALTY_PROPERTY_COLUMN_EXPECTED_DEPOSIT_AMOUNT = "EXPECTED_DEPOSIT_AMOUNT";
    String DB_REALTY_PROPERTY_COLUMN_EXPECTED_RENTAL_AMOUNT = "EXPECTED_RENTAL_AMOUNT";

    String DB_REALTY_PROPERTY_COLUMN_EXPECTED_AMOUNT = "EXPECTED_AMOUNT";
    String DB_REALTY_PROPERTY_COLUMN_ALL_INCLUSIVE_PRICE = "ALL_INCLUSIVE_PRICE";
    String DB_REALTY_PROPERTY_COLUMN_TAX_AND_GOV_CHARGE_INCLUDED = "TAX_AND_GOV_CHARGE_INCLUDED";

    String DB_REALTY_PROPERTY_COLUMN_TOTAL_BROKER = "TOTAL_BROKER";

    String DB_REALTY_PROPERTY_COLUMN_WEEKDAYS_VISIT_TIME_IDS = "WEEKDAYS_VISIT_TIME_IDS";
    String DB_REALTY_PROPERTY_COLUMN_WEEKDAYS_VISIT_TIME_TITLES = "WEEKDAYS_VISIT_TIME_TITLES";
    String DB_REALTY_PROPERTY_COLUMN_WEEKEND_VISIT_TIME_IDS = "WEEKEND_VISIT_TIME_IDS";
    String DB_REALTY_PROPERTY_COLUMN_WEEKEND_VISIT_TIME_TITLES = "WEEKEND_VISIT_TIME_TITLES";

    String DB_REALTY_PROPERTY_COLUMN_EARTHQUAKE_RESISTANT = "EARTHQUAKE_RESISTANT";
    String DB_REALTY_PROPERTY_COLUMN_GAS_PIPELINE = "GAS_PIPELINE";
    String DB_REALTY_PROPERTY_COLUMN_CLUB_HOUSE = "CLUB_HOUSE";
    String DB_REALTY_PROPERTY_COLUMN_GYM = "GYM";

    String DB_REALTY_PROPERTY_COLUMN_KIDS_PLAY_AREA = "KIDS_PLAY_AREA";
    String DB_REALTY_PROPERTY_COLUMN_WATER_HARVESTING = "WATER_HARVESTING";
    String DB_REALTY_PROPERTY_COLUMN_SWIMMING_POOL = "SWIMMING_POOL";
    String DB_REALTY_PROPERTY_COLUMN_COMMON_AREA_POWER_BACKUP = "COMMON_AREA_POWER_BACKUP";

    String DB_REALTY_PROPERTY_COLUMN_FLAT_POWER_BACKUP = "FLAT_POWER_BACKUP";

    String DB_REALTY_PROPERTY_COLUMN_SENIOR_CITIZEN_AREA = "SENIOR_CITIZEN_AREA";
    String DB_REALTY_PROPERTY_COLUMN_GATED_SOCIETY = "GATED_SOCIETY";
    String DB_REALTY_PROPERTY_COLUMN_WATER_SUPPLY = "WATER_SUPPLY";

    String DB_REALTY_PROPERTY_COLUMN_LANDSCAPE_LAWN = "LANDSCAPE_LAWN";
    String DB_REALTY_PROPERTY_COLUMN_BANQUET_HALL = "BANQUET_HALL";
    String DB_REALTY_PROPERTY_COLUMN_JOGGERS_TRACK = "JOGGERS_TRACK";
    String DB_REALTY_PROPERTY_COLUMN_CCTV = "CCTV";

    String DB_REALTY_PROPERTY_COLUMN_FIRE_ALARM = "FIRE_ALARM";
    String DB_REALTY_PROPERTY_COLUMN_PET_FRIENDLY = "PET_FRIENDLY";

    String DB_REALTY_PROPERTY_COLUMN_TOTAL_SERVICE_LIFT = "TOTAL_SERVICE_LIFT";
    String DB_REALTY_PROPERTY_COLUMN_TOTAL_LIFT = "TOTAL_LIFT";

    String DB_REALTY_PROPERTY_COLUMN_OC_TS = "OC_TS";


    String DB_REALTY_BUILDING_TEMPLATE_COLUMNS = " PROJECT_NAME, PROPERTY_TYPE_ID, PROPERTY_TYPE_TITLE, PROPERTY_TYPE_GROUP_ID, PROPERTY_TYPE_GROUP_TITLE, BUILDING_NAME, BUILDER_NAME, BUILDER_WEB_URL, AVAILABILITY_ID, AVAILABILITY_TITLE, AVAILABILITY_TS, PROPERTY_AGE_ID, PROPERTY_AGE_TITLE, ADDRESS_LINE_1, ADDRESS_LINE_2, LOCALITY_IDS, LOCALITY_TITLES, CITY_NAME, STATE_NAME, LANDMARK_NAME, PIN_CODE, COUNTRY_NAME, TOTAL_FLOORS, TOTAL_FLATS_FLOOR, TOTAL_BUILDING_COVERED_PARKING, TOTAL_BUILDING_OPEN_PARKING, TOTAL_BUILDING_VISITOR_PARKING, TOTAL_SERVICE_LIFT, TOTAL_LIFT, OC_TS, RERA_ID, PROPERTY_DESCRIPTION, EARTHQUAKE_RESISTANT, GAS_PIPELINE, CLUB_HOUSE, GYM, KIDS_PLAY_AREA, WATER_HARVESTING, SWIMMING_POOL, COMMON_AREA_POWER_BACKUP, FLAT_POWER_BACKUP, SENIOR_CITIZEN_AREA, GATED_SOCIETY, WATER_SUPPLY, LANDSCAPE_LAWN, BANQUET_HALL, JOGGERS_TRACK, CCTV, FIRE_ALARM, PET_FRIENDLY, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS " ;
    String DB_REALTY_POST_PROPERTY_COLUMNS = DB_REALTY_BUILDING_TEMPLATE_COLUMNS + ", TEMPLATE_ID, TRANSACTION_TYPE_ID, TRANSACTION_TYPE_TITLE, CONFIGURATION_ID, CONFIGURATION_TITLE, TOTAL_BEDROOMS, TOTAL_MASTER_BEDROOMS, TOTAL_BATHROOMS, TOTAL_BALCONIES, SUPER_BUILT_UP_AREA, SUPER_BUILT_UP_AREA_UNIT_ID, SUPER_BUILT_UP_AREA_UNIT_TITLE, BUILT_UP_AREA, BUILT_UP_AREA_UNIT_ID, BUILT_UP_AREA_UNIT_TITLE, CARPET_AREA, CARPET_AREA_UNIT_ID, CARPET_AREA_UNIT_TITLE, FURNISH_TYPE_ID, FURNISH_TYPE_TITLE, FLOOR_ID, FLOOR_NO, TOTAL_COVERED_PARKING, TOTAL_OPEN_PARKING, FACE_ID, FACE_TITLE, OVERLOOK_IDS, OVERLOOK_TITLES, FLOOR_TYPE_IDS, FLOOR_TYPE_TITLES, AMOUNT_NEGOTIABLE, MAINTENANCE_AMOUNT, MAINTENANCE_PERIOD_ID, MAINTENANCE_PERIOD_TITLE, MODULAR_KITCHEN, POOJA_ROOM, STUDY_ROOM, SERVANT_ROOM, OTHERS_ROOM, NOTES, TOTAL_BROKER, WEEKDAYS_VISIT_TIME_IDS, WEEKDAYS_VISIT_TIME_TITLES, WEEKEND_VISIT_TIME_IDS, WEEKEND_VISIT_TIME_TITLES, HEAVY_DEPOSIT, EXPECTED_DEPOSIT_AMOUNT, EXPECTED_RENTAL_AMOUNT, EXPECTED_AMOUNT, ALL_INCLUSIVE_PRICE, TAX_AND_GOV_CHARGE_INCLUDED " ;

    String DB_REALTY_BUILDING_TEMPLATE_COLUMNS_PARAMS = " :PROJECT_NAME, :PROPERTY_TYPE_ID, :PROPERTY_TYPE_TITLE, :PROPERTY_TYPE_GROUP_ID, :PROPERTY_TYPE_GROUP_TITLE, :BUILDING_NAME, :BUILDER_NAME, :BUILDER_WEB_URL, :AVAILABILITY_ID, :AVAILABILITY_TITLE, :AVAILABILITY_TS, :PROPERTY_AGE_ID, :PROPERTY_AGE_TITLE, :ADDRESS_LINE_1, :ADDRESS_LINE_2, :LOCALITY_IDS, :LOCALITY_TITLES, :CITY_NAME, :STATE_NAME, :LANDMARK_NAME, :PIN_CODE, :COUNTRY_NAME, :TOTAL_FLOORS, :TOTAL_FLATS_FLOOR, :TOTAL_BUILDING_COVERED_PARKING, :TOTAL_BUILDING_OPEN_PARKING, :TOTAL_BUILDING_VISITOR_PARKING, :TOTAL_SERVICE_LIFT, :TOTAL_LIFT, :OC_TS, :RERA_ID, :PROPERTY_DESCRIPTION, :EARTHQUAKE_RESISTANT, :GAS_PIPELINE, :CLUB_HOUSE, :GYM, :KIDS_PLAY_AREA, :WATER_HARVESTING, :SWIMMING_POOL, :COMMON_AREA_POWER_BACKUP, :FLAT_POWER_BACKUP, :SENIOR_CITIZEN_AREA, :GATED_SOCIETY, :WATER_SUPPLY, :LANDSCAPE_LAWN, :BANQUET_HALL, :JOGGERS_TRACK, :CCTV, :FIRE_ALARM, :PET_FRIENDLY, :STATUS_ID, :STATUS_TITLE, :CREATED_BY, :CREATED_TS, :UPDATED_BY, :UPDATED_TS " ;
    String DB_REALTY_POST_PROPERTY_COLUMNS_PARAMS = DB_REALTY_BUILDING_TEMPLATE_COLUMNS_PARAMS + ", :TEMPLATE_ID, :TRANSACTION_TYPE_ID, :TRANSACTION_TYPE_TITLE, :CONFIGURATION_ID, :CONFIGURATION_TITLE, :TOTAL_BEDROOMS, :TOTAL_MASTER_BEDROOMS, :TOTAL_BATHROOMS, :TOTAL_BALCONIES, :SUPER_BUILT_UP_AREA, :SUPER_BUILT_UP_AREA_UNIT_ID, :SUPER_BUILT_UP_AREA_UNIT_TITLE, :BUILT_UP_AREA, :BUILT_UP_AREA_UNIT_ID, :BUILT_UP_AREA_UNIT_TITLE, :CARPET_AREA, :CARPET_AREA_UNIT_ID, :CARPET_AREA_UNIT_TITLE, :FURNISH_TYPE_ID, :FURNISH_TYPE_TITLE, :FLOOR_ID, :FLOOR_NO, :TOTAL_COVERED_PARKING, :TOTAL_OPEN_PARKING, :FACE_ID, :FACE_TITLE, :OVERLOOK_IDS, :OVERLOOK_TITLES, :FLOOR_TYPE_IDS, :FLOOR_TYPE_TITLES, :AMOUNT_NEGOTIABLE, :MAINTENANCE_AMOUNT, :MAINTENANCE_PERIOD_ID, :MAINTENANCE_PERIOD_TITLE, :MODULAR_KITCHEN, :POOJA_ROOM, :STUDY_ROOM, :SERVANT_ROOM, :OTHERS_ROOM, :NOTES, :TOTAL_BROKER, :WEEKDAYS_VISIT_TIME_IDS, :WEEKDAYS_VISIT_TIME_TITLES, :WEEKEND_VISIT_TIME_IDS, :WEEKEND_VISIT_TIME_TITLES, :HEAVY_DEPOSIT, :EXPECTED_DEPOSIT_AMOUNT, :EXPECTED_RENTAL_AMOUNT, :EXPECTED_AMOUNT, :ALL_INCLUSIVE_PRICE, :TAX_AND_GOV_CHARGE_INCLUDED " ;


    // ====================   Param Constant   =======================


    // ====================   SELECT/INSERT/UPDATE/DELETE Constant   =======================

    String DB_REALTY_BUILDING_TEMPLATE_SELECT = "SELECT TEMPLATE_ID, " + DB_REALTY_BUILDING_TEMPLATE_COLUMNS + " FROM BUILDING_TEMPLATE WHERE 1 = 1 ";
    String DB_REALTY_POST_PROPERTY_SELECT = "SELECT PROPERTY_ID, " + DB_REALTY_POST_PROPERTY_COLUMNS + " FROM POST_PROPERTY WHERE 1 = 1 ";
    String DB_REALTY_BUILDING_TEMPLATE_INSERT = "INSERT INTO BUILDING_TEMPLATE (" + DB_REALTY_BUILDING_TEMPLATE_COLUMNS + ") VALUES (" +  DB_REALTY_BUILDING_TEMPLATE_COLUMNS_PARAMS + ") ";
    String DB_REALTY_POST_PROPERTY_INSERT = "INSERT INTO POST_PROPERTY (" + DB_REALTY_POST_PROPERTY_COLUMNS + ") VALUES (" +  DB_REALTY_POST_PROPERTY_COLUMNS_PARAMS + ") ";

}
