package com.paroont.core.db.constant.profile;

public interface CoreProfileDbConst {

    // ====================   Column Constant   =======================

    String DB_COMMON_USER_PROFILE_COLUMN_PROFILE_TYPE_ID = "PROFILE_TYPE_ID";
    String DB_COMMON_USER_PROFILE_COLUMN_PROFILE_TYPE_TITLE = "PROFILE_TYPE_TITLE";

    String DB_COMMON_USER_PROFILE_COLUMN_INCOME_RANGE_ID = "INCOME_RANGE_ID";
    String DB_COMMON_USER_PROFILE_COLUMN_INCOME_RANGE_TITLE = "INCOME_RANGE_TITLE";

    String DB_COMMON_USER_PROFILE_COLUMNS = " FIRST_NAME, LAST_NAME, MOBILE_NO, MOBILE_COUNTRY_CODE, EMAIL_ID, STATUS_ID, STATUS_TITLE, PROFILE_TYPE_ID, PROFILE_TYPE_TITLE,  FACEBOOK_ID, TWITTER_ID, INSTAGRAM_ID, WHATSAPP_NO, WHATSAPP_COUNTRY_CODE,  EMAIL_ID_2, EMAIL_ID_3, CONTACT_NO_2, CONTACT_NO_2_COUNTRY_CODE, CONTACT_NO_2_TITLE, CONTACT_NO_3, CONTACT_NO_3_COUNTRY_CODE, CONTACT_NO_3_TITLE, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY_NAME, STATE_NAME, LANDMARK_NAME, PIN_CODE, COUNTRY_NAME, GENDER_TITLE, DOB, INCOME_RANGE_ID, INCOME_RANGE_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS  ";

    String DB_COMMON_USER_PROFILE_COLUMNS_PARAMS = " :FIRST_NAME, :LAST_NAME, :MOBILE_NO, :MOBILE_COUNTRY_CODE, :EMAIL_ID, :STATUS_ID, :STATUS_TITLE, :PROFILE_TYPE_ID, :PROFILE_TYPE_TITLE,  :FACEBOOK_ID, :TWITTER_ID, :INSTAGRAM_ID, :WHATSAPP_NO, :WHATSAPP_COUNTRY_CODE,  :EMAIL_ID_2, :EMAIL_ID_3, :CONTACT_NO_2, :CONTACT_NO_2_COUNTRY_CODE, :CONTACT_NO_2_TITLE, :CONTACT_NO_3, :CONTACT_NO_3_COUNTRY_CODE, :CONTACT_NO_3_TITLE, :ADDRESS_LINE_1, :ADDRESS_LINE_2, :CITY_NAME, :STATE_NAME, :LANDMARK_NAME, :PIN_CODE, :COUNTRY_NAME, :GENDER_TITLE, :DOB, :INCOME_RANGE_ID, :INCOME_RANGE_TITLE, :CREATED_BY, :CREATED_TS, :UPDATED_BY, :UPDATED_TS  ";

    String DB_COMMON_COMPANY_PROFILE_COLUMNS = DB_COMMON_USER_PROFILE_COLUMNS + ", COMPANY_NAME, COMPANY_WEB_URL, COMPANY_OVERVIEW " ;
    String DB_COMMON_COMPANY_PROFILE_COLUMNS_PARAMS = DB_COMMON_USER_PROFILE_COLUMNS_PARAMS + ", :COMPANY_NAME, :COMPANY_WEB_URL, :COMPANY_OVERVIEW " ;

    String DB_COMMON_COMPANY_PROFILE_COLUMN_COMPANY_NAME = "COMPANY_NAME";
    String DB_COMMON_COMPANY_PROFILE_COLUMN_COMPANY_WEB_URL = "COMPANY_WEB_URL";
    String DB_COMMON_COMPANY_PROFILE_COLUMN_COMPANY_OVERVIEW = "COMPANY_OVERVIEW";

    // ====================   Param Constant   =======================


    // ====================   SELECT/INSERT/UPDATE/DELETE Constant   ======================= ,RERA_ID, FROM USER_PROFILE WHERE 1 = 1

    String DB_COMMON_USER_PROFILE_SELECT = "SELECT USER_ID, " + DB_COMMON_USER_PROFILE_COLUMNS + " FROM USER_PROFILE WHERE 1 = 1 ";
    String DB_COMMON_COMPANY_PROFILE_SELECT = "SELECT USER_ID, " + DB_COMMON_COMPANY_PROFILE_COLUMNS + " FROM USER_PROFILE WHERE 1 = 1 ";


    String DB_COMMON_USER_PROFILE_INSERT = "INSERT INTO USER_PROFILE (" + DB_COMMON_USER_PROFILE_COLUMNS + ") VALUES (" +  DB_COMMON_USER_PROFILE_COLUMNS_PARAMS + ") ";
    String DB_COMMON_COMPANY_PROFILE_INSERT = "INSERT INTO USER_PROFILE (" + DB_COMMON_COMPANY_PROFILE_COLUMNS + ") VALUES (" +  DB_COMMON_COMPANY_PROFILE_COLUMNS_PARAMS + ") ";

}
