
/*  ============ APP_REF_DATA ====================  */


/* ====================== COMMON_STATUS ==================== */
INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('COMMON_STATUS', '1','Active','DEFAULT', NULL, 'COMMON', 'COMMON', 1, 'Active', 'system-user', 'system-user');

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('COMMON_STATUS', '2','Inactive','DEFAULT', NULL, 'COMMON', 'COMMON', 1, 'Active', 'system-user', 'system-user');


/*  ====================== CONTACT_TYPE ====================  */

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('CONTACT_TYPE', '1','Mobile','DEFAULT', NULL, 'COMMON', 'COMMON', 1, 'Active', 'system-user', 'system-user');

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('CONTACT_TYPE', '2','Work','DEFAULT', NULL, 'COMMON', 'COMMON', 1, 'Active', 'system-user', 'system-user');

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('CONTACT_TYPE', '3','Home','DEFAULT', NULL, 'COMMON', 'COMMON', 1, 'Active', 'system-user', 'system-user');

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('CONTACT_TYPE', '4','Other','DEFAULT', NULL, 'COMMON', 'COMMON', 1, 'Active', 'system-user', 'system-user');


/*  ====================== PROPERTY_TYPE_GROUP ====================  */
INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('PROPERTY_TYPE_GROUP', '1','Residential','DEFAULT', NULL, 'REALTY', 'PROPERTY', 1, 'Active', 'system-user', 'system-user');

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, APP_NAME, MODULE_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, UPDATED_BY)
VALUES ('PROPERTY_TYPE_GROUP', '2','Commercial','DEFAULT', NULL, 'REALTY', 'PROPERTY', 1, 'Active', 'system-user', 'system-user');


