
/*  ============ APP_REF_DATA ====================  */


/* ====================== COMMON_STATUS ==================== */
INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS)
VALUES ('COMMON_STATUS', '1','Active','DEFAULT', NULL, 1, 'Active', 'system-user', CURRENT_TIMESTAMP, 'system-user', CURRENT_TIMESTAMP);

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS)
VALUES ('COMMON_STATUS', '2','Inactive','DEFAULT', NULL, 1, 'Active', 'system-user', CURRENT_TIMESTAMP, 'system-user', CURRENT_TIMESTAMP);


/*  ====================== CONTACT_TYPE ====================  */

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS)
VALUES ('CONTACT_TYPE', '1','Mobile','DEFAULT', NULL, 1, 'Active', 'system-user', CURRENT_TIMESTAMP, 'system-user', CURRENT_TIMESTAMP);

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS)
VALUES ('CONTACT_TYPE', '2','Work','DEFAULT', NULL, 1, 'Active', 'system-user', CURRENT_TIMESTAMP, 'system-user', CURRENT_TIMESTAMP);

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS)
VALUES ('CONTACT_TYPE', '3','Home','DEFAULT', NULL, 1, 'Active', 'system-user', CURRENT_TIMESTAMP, 'system-user', CURRENT_TIMESTAMP);

INSERT INTO APP_REF_DATA (DATA_TYPE, DATA_KEY, DATA_VALUE, GROUP_NAME, SUB_GROUP_NAME, STATUS_ID, STATUS_TITLE, CREATED_BY, CREATED_TS, UPDATED_BY, UPDATED_TS)
VALUES ('CONTACT_TYPE', '4','Other','DEFAULT', NULL, 1, 'Active', 'system-user', CURRENT_TIMESTAMP, 'system-user', CURRENT_TIMESTAMP);

